#+title: ZSH Configuration
#+AUTHOR: Evan Erickson (EE)
#+STARTUP: showeverything
#+PROPERTY: header-args:shell :tangle ./zshrc
#+auto-tangle: t

* TABLE OF CONTENTS :toc:
- [[#about-this-config][ABOUT THIS CONFIG]]
- [[#powerlevel10k-settings][POWERLEVEL10K SETTINGS]]
- [[#aliases][ALIASES]]
  - [[#changing-ls-to-exa][Changing "ls" to "exa"]]
  - [[#yt-dlp][yt-dlp]]
  - [[#open-in-emacs][Open in Emacs]]
  - [[#scripts][Scripts]]
  - [[#shortcuts][Shortcuts]]
  - [[#random-aliases][Random Aliases]]
  - [[#homebrew][Homebrew]]
  - [[#app-management][App Management]]
  - [[#moving-to-server][Moving to Server]]
- [[#customize-prompts][Customize Prompt(s)]]

* ABOUT THIS CONFIG
This files is used to configure my zshrc

* POWERLEVEL10K SETTINGS
Enable Powerlevel10k instant prompt. Should stay close to the top of $HOME/.zshrc. Initialization code that may require console input (password prompts, [y/n] confirmations, etc.) must go above this block; everything else may go below.

#+begin_src shell
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi
#+end_src

If you come from bash you might have to change your $PATH.

#+begin_src shell
# export PATH=$HOME/bin:/opt/homebrew/bin:/usr/local/bin:$PATH
#+end_src

#+RESULTS:

Path to your oh-my-zsh installation.

#+begin_src shell
#export ZSH="/Users/eerickson/.oh-my-zsh"
export ZSH="$HOME/.oh-my-zsh"
#+end_src

Path to brew.

#+begin_src shell
# eval "$(/opt/homebrew/bin/brew shellenv)"
#+end_src

Set name of the theme to load --- if set to "random", it will load a random theme each time oh-my-zsh is loaded, in which case, to know which specific one was loaded, run: echo $RANDOM_THEME See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes

#+begin_src shell
ZSH_THEME="powerlevel10k/powerlevel10k"
#+end_src

Set list of themes to pick from when loading at random Setting this variable when ZSH_THEME=random will cause zsh to load a theme from this variable instead of looking in $ZSH/themes/ If set to an empty array, this variable will have no effect.

#+begin_src shell
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )
#+end_src

Uncomment the following line to use case-sensitive completion.

#+begin_src shell
# CASE_SENSITIVE="true"
#+end_src

Uncomment the following line to use hyphen-insensitive completion. Case-sensitive completion must be off. _ and - will be interchangeable.

#+begin_src shell
# HYPHEN_INSENSITIVE="true"
#+end_src

Uncomment the following line to disable bi-weekly auto-update checks.

#+begin_src shell
# DISABLE_AUTO_UPDATE="true"
#+end_src

Uncomment the following line to automatically update without prompting.

#+begin_src shell
# DISABLE_UPDATE_PROMPT="true"
#+end_src

Uncomment the following line to change how often to auto-update (in days).

#+begin_src shell
# export UPDATE_ZSH_DAYS=13
#+end_src

Uncomment the following line if pasting URLs and other text is messed up.

#+begin_src shell
# DISABLE_MAGIC_FUNCTIONS="true"
#+end_src

Uncomment the following line to disable colors in ls.

#+begin_src shell
# DISABLE_LS_COLORS="true"
#+end_src

Uncomment the following line to disable auto-setting terminal title.

#+begin_src shell
# DISABLE_AUTO_TITLE="true"
#+end_src

Uncomment the following line to enable command auto-correction.

#+begin_src shell
# ENABLE_CORRECTION="true"
#+end_src

Uncomment the following line to display red dots whilst waiting for completion. Caution: this setting can cause issues with multiline prompts (zsh 5.7.1 and newer seem to work) See https://github.com/ohmyzsh/ohmyzsh/issues/5765

#+begin_src shell
# COMPLETION_WAITING_DOTS="true"
#+end_src

Uncomment the following line if you want to disable marking untracked files under VCS as dirty. This makes repository status check for large repositories much, much faster.

#+begin_src shell
# DISABLE_UNTRACKED_FILES_DIRTY="true"
#+end_src

Uncomment the following line if you want to change the command execution time stamp shown in the history command output. You can set one of the optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd" or set a custom format using the strftime function format specifications, see 'man strftime' for details.

#+begin_src shell
# HIST_STAMPS="mm/dd/yyyy"
#+end_src

Would you like to use another custom folder than $ZSH/custom?

#+begin_src shell
# ZSH_CUSTOM=/path/to/new-custom-folder
#+end_src

Which plugins would you like to load?
Standard plugins can be found in $ZSH/plugins/
Custom plugins may be added to $ZSH_CUSTOM/plugins/
Example format: plugins=(rails git textmate ruby lighthouse)
Add wisely, as too many plugins slow down shell startup.

#+begin_src shell
plugins=(git)

source $ZSH/oh-my-zsh.sh

export PATH=/usr/local/opt/llvm/bin:$PATH
export PATH=/opt/homebrew/bin:/opt/homebrew/sbin:$HOME/bin:$PATH
export PATH=$HOME/.local/bin:$PATH
export PATH=$HOME/.emacs.d/bin/:$PATH
#+end_src

User configuration

#+begin_src shell
# export MANPATH="/usr/local/man:$MANPATH"
#+end_src

You may need to manually set your language environment

#+begin_src shell
# export LANG=en_US.UTF-8
#+end_src

Preferred editor for local and remote sessions

#+begin_src shell
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi
#+end_src

Compilation flags

#+begin_src shell
# export ARCHFLAGS="-arch x86_64"
#+end_src

Set personal aliases, overriding those provided by oh-my-zsh libs, plugins, and themes. Aliases can be placed here, though oh-my-zsh users are encouraged to define aliases within the ZSH_CUSTOM folder. For a full list of active aliases, run `alias`.

Example aliases
#+begin_src shell
# alias zshconfig="mate $HOME/.zshrc"
# alias ohmyzsh="mate $HOME/.oh-my-zsh"
#+end_src

emacs

#+begin_src shell
alias doomsync="$HOME/.emacs.d/bin/doom sync"
alias doomdoctor="$HOME/.emacs.d/bin/doom doctor"
alias doomupgrade="$HOME/.emacs.d/bin/doom upgrade"
alias doompurge="$HOME/.emacs.d/bin/doom purge"
alias doomclean="$HOME/.emacs.d/bin/doom clean"
alias doomreset="rm -rf $HOME/.emacs.d/.local/straight && doomsync"
#+end_src

youtube-dl

#+begin_src shell
# alias yta-aac="youtube-dl --extract-audio --audio-format aac "
# alias yta-best="youtube-dl --extract-audio --audio-format best "
# alias yta-flac="youtube-dl --extract-audio --audio-format flac "
# alias yta-m4a="youtube-dl --extract-audio --audio-format m4a "
# alias yta-mp3="youtube-dl --extract-audio --audio-format mp3 "
# alias yta-opus="youtube-dl --extract-audio --audio-format opus "
# alias yta-vorbis="youtube-dl --extract-audio --audio-format vorbis "
# alias yta-wav="youtube-dl --extract-audio --audio-format wav "
# alias ytv-best="youtube-dl -f bestvideo+bestaudio "
#+end_src

To customize prompt, run `p10k configure` or edit $HOME/.p10k.zsh.

#+begin_src shell
[[ ! -f $HOME/.p10k.zsh ]] || source $HOME/.p10k.zsh
#+end_src

Set Variables
Syntax highlighting for man pages using bat

#+begin_src shell
export MANPAGER="sh -c 'col -bx | bat -l man -p'"
#+end_src

Change ZSH Options

* ALIASES
** Changing "ls" to "exa"

#+begin_src shell
alias ls='exa -alF --color=always --group-directories-first' # my preferred listing
alias la='exa -aF --color=always --group-directories-first'  # all files and dirs
alias ll='exa -lF --color=always --group-directories-first'  # long format
alias lt='exa -aT --level=2 --color=always --group-directories-first' # tree listing
alias l.='exa -a | egrep "^\."'
#+end_src

** yt-dlp

#+begin_src shell
alias yta-best="yt-dlp --extract-audio --audio-format best "
alias ytv-best="yt-dlp -f bestvideo+bestaudio --merge-output-format mkv "
alias ytd="yt-dlp -f "
alias ytl="yt-dlp -F "
#+end_src

** Open in Emacs

#+begin_src shell
alias doom-config="open -a emacs $HOME/.doom.d/config.org"
alias doom-pack="open -a emacs $HOME/.doom.d/packages.el"
alias doom-init="open -a emacs $HOME/.doom.d/init.el"
alias doom-open="open -a emacs "
alias zsh-config="open -a emacs $HOME/.zshrc"
alias emacs="open -a emacs"
#+end_src

** Scripts

#+begin_src shell
alias dotpdf="$HOME/.dotfiles/scripts/dot2pdf.sh"
alias c320="$HOME/.dotfiles/scripts/convert_to_320_aac.sh . $HOME/Music/encoded"
alias c96="$HOME/.dotfiles/scripts/convert_to_96_aac.sh . $HOME/Music/encoded"
#+end_src

** Shortcuts

#+begin_src shell
alias dev="cd $HOME/dev"
alias dotfiles="cd $HOME/.dotfiles"
alias rep="cd $HOME/dev/PhaseChangeProjects/Representation"
alias repwork="cd $HOME/dev/PhaseChangeProjects/Representation/workspace"
alias icgen="cd $HOME/dev/PhaseChangeProjects/icGenerator"
alias icgenviz="cd $HOME/dev/PhaseChangeProjects/icGenerator/src/main/resources/tmp"
alias gotosync="cp -a $HOME/.dotfiles/obsidian/GoTo\ Elimination/. $HOME/dev/fom/GraphNormaliztion/Goto\ Elimination\ Docs"
alias pullrep="rep && $HOME/.dotfiles/scripts/mvOutVizCode.sh && git restore src/* && git pull && $HOME/.dotfiles/scripts/mvInVizCode.sh"
alias moveoutrep="$HOME/.dotfiles/scripts/mvOutVizCode.sh"
alias moveinrep="$HOME/.dotfiles/scripts/mvInVizCode.sh"
alias dotclean="rm *.dot *.pdf"
#+end_src

** Random Aliases

#+begin_src shell
alias python="python3"
alias pip="pip3"
#+end_src

** Homebrew

#+begin_src shell
# alias brew="/opt/homebrew/bin/brew"
alias brewupdate="echo 'Updating Homebrew and Casks' && brew cu -af && echo 'Upgrading Packages' && brew upgrade"
#+end_src

** App Management

#+begin_src shell
alias updateapps="echo 'Updating Homebrew and Casks...' && brew cu -af && echo 'Upgrading Packages...' && brew upgrade && echo 'Updating Apps from App Store...' && mas upgrade && echo 'Updating Doom Emacs...' && doomupgrade && doomdoctor & doomsync"
alias deletezsh="echo 'Delete $HOME/.oh-my-zsh/custom' && rm $HOME/.oh-my-zsh/custom && echo 'Updating ZSH' && exec zsh -l"
alias linkzsh="echo 'Relink .oh-my-zsh/custom' && $HOME/.dotfiles/install && sleep 1s && exec zsh"
#+end_src

** Moving to Server

#+begin_src shell
alias mv4k="echo 'Moving 4K movies to server...' && mv $HOME/inbox/00_movies_4k_to_transfer/* /Volumes/files/plex/movies_4k/"
alias mvmovies="echo 'Moving movies to server...' && mv $HOME/inbox/00_movies_to_transfer/* /Volumes/files/plex/movies/"
alias mvporn="echo 'Moving porn to server...' && mv $HOME/inbox/00_porn_to_transfer/* /Volumes/files/plex/videos/"
alias mvfiles="mv4k && mvmovies && mvporn"
#+end_src

* Customize Prompt(s)

Add locations to $PATH variables

Write Handy Functions

#+begin_src shell
function mkcd() {
  mkdir -p "$@" && cd "$_";
}
#+end_src

Use ZSH Plugins

...and Other Surprises

To customize prompt, run `p10k configure` or edit $HOME/.dotfiles/p10k.zsh.

#+begin_src shell
[[ ! -f $HOME/.dotfiles/p10k.zsh ]] || source $HOME/.dotfiles/p10k.zsh
#+end_src
