#+title: ZSH Configuration
#+AUTHOR: Evan Erickson (EE)
#+PROPERTY: header-args:sh :tangle ./zshrc_full
#+auto-tangle: t
#+STARTUP: showeverything

* TABLE OF CONTENTS :toc:
- [[#about-this-config][ABOUT THIS CONFIG]]
- [[#powerlevel10k-settings][POWERLEVEL10K SETTINGS]]
- [[#aliases][ALIASES]]
  - [[#changing-ls-to-exa][Changing "ls" to "exa"]]
  - [[#yt-dlp][yt-dlp]]
  - [[#open-in-emacs][Open in Emacs]]
  - [[#scripts][Scripts]]
  - [[#shortcuts][Shortcuts]]
  - [[#random-aliases][Random Aliases]]
  - [[#homebrew][Homebrew]]
  - [[#app-management][App Management]]
- [[#customize-prompts][Customize Prompt(s)]]
- [[#source-external-shell-info][Source External Shell Info]]

* ABOUT THIS CONFIG
This files is used to configure my zshrc

* POWERLEVEL10K SETTINGS
Enable Powerlevel10k instant prompt. Should stay close to the top of $HOME/.zshrc. Initialization code that may require console input (password prompts, [y/n] confirmations, etc.) must go above this block; everything else may go below.

#+begin_src sh
#!/usr/bin/env zsh

if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi
#+end_src

If you come from bash you might have to change your $PATH.

#+begin_src sh
# export PATH=$HOME/bin:/opt/homebrew/bin:/usr/local/bin:$PATH
#+end_src

Path to your oh-my-zsh installation.

#+begin_src sh
#export ZSH="/Users/eerickson/.oh-my-zsh"
export ZSH="$HOME/.oh-my-zsh"
#+end_src

Path to brew.

#+begin_src sh
# eval "$(/opt/homebrew/bin/brew shenv)"
#+end_src

Set name of the theme to load --- if set to "random", it will load a random theme each time oh-my-zsh is loaded, in which case, to know which specific one was loaded, run: echo $RANDOM_THEME See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes

#+begin_src sh
ZSH_THEME="powerlevel10k/powerlevel10k"
#+end_src

Set list of themes to when loading at random Setting this variable when ZSH_THEME=random will cause zsh to load a theme from this variable instead of looking in $ZSH/themes/ If set to an empty array, this variable will have no effect.

#+begin_src sh
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )
#+end_src

Uncomment the following line to use case-sensitive completion.

#+begin_src sh
# CASE_SENSITIVE="true"
#+end_src

Uncomment the following line to use hyphen-insensitive completion. Case-sensitive completion must be off. _ and - will be interchangeable.

#+begin_src sh
# HYPHEN_INSENSITIVE="true"
#+end_src

Uncomment the following line to disable bi-weekly auto-update checks.

#+begin_src sh
# DISABLE_AUTO_UPDATE="true"
#+end_src

Uncomment the following line to automatically update without prompting.

#+begin_src sh
# DISABLE_UPDATE_PROMPT="true"
#+end_src

Uncomment the following line to change how often to auto-update (in days).

#+begin_src sh
# export UPDATE_ZSH_DAYS=13
#+end_src

Uncomment the following line if pasting URLs and other text is messed up.

#+begin_src sh
# DISABLE_MAGIC_FUNCTIONS="true"
#+end_src

Uncomment the following line to disable colors in ls.

#+begin_src sh
# DISABLE_LS_COLORS="true"
#+end_src

Uncomment the following line to disable auto-setting terminal title.

#+begin_src sh
# DISABLE_AUTO_TITLE="true"
#+end_src

Uncomment the following line to enable command auto-correction.

#+begin_src sh
# ENABLE_CORRECTION="true"
#+end_src

Uncomment the following line to display red dots whilst waiting for completion. Caution: this setting can cause issues with multiline prompts (zsh 5.7.1 and newer seem to work) See https://github.com/ohmyzsh/ohmyzsh/issues/5765

#+begin_src sh
# COMPLETION_WAITING_DOTS="true"
#+end_src

Uncomment the following line if you want to disable marking untracked files under VCS as dirty. This makes repository status check for large repositories much, much faster.

#+begin_src sh
# DISABLE_UNTRACKED_FILES_DIRTY="true"
#+end_src

Uncomment the following line if you want to change the command execution time stamp shown in the history command output. You can set one of the optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd" or set a custom format using the strftime function format specifications, see 'man strftime' for details.

#+begin_src sh
# HIST_STAMPS="mm/dd/yyyy"
#+end_src

Would you like to use another custom folder than $ZSH/custom?

#+begin_src sh
# ZSH_CUSTOM=/path/to/new-custom-folder
#+end_src

Which plugins would you like to load?
Standard plugins can be found in $ZSH/plugins/
Custom plugins may be added to $ZSH_CUSTOM/plugins/
Example format: plugins=(rails git textmate ruby lighthouse)
Add wisely, as too many plugins slow down sh startup.

#+begin_src sh
plugins=(git)

source $ZSH/oh-my-zsh.sh

export PATH=/opt/homebrew/bin:/opt/homebrew/sbin:$HOME/bin:$PATH
export PATH=$HOME/.local/bin:$PATH
export PATH=$HOME/.emacs.d/bin/:$PATH
export HOMEBREW_CASK_OPTS="--no-quarantine"

# export PATH="/Library/Java/JavaVirtualMachines/graalvm-ce-java11-22.2.0/Contents/Home/bin:$PATH"
# export JAVA_HOME="/Library/Java/JavaVirtualMachines/graalvm-ce-java11-22.2.0/Contents/Home"

export DEFAULT_MVN_VERSION=3.6.3

# export PATH="/usr/local/opt/openjdk@11/bin:$PATH"
# export JAVA_HOME="/Library/Java/JavaVirtualMachines/openjdk-11.jdk/Contents/Home"

# export PATH="/Library/Java/JavaVirtualMachines/jdk-11.0.8.jdk/Contents/Home/bin:$PATH"
# export JAVA_HOME="/Library/Java/JavaVirtualMachines/jdk-11.0.8.jdk/Contents/Home"

#+end_src

User configuration

#+begin_src sh
# export MANPATH="/usr/local/man:$MANPATH"
#+end_src

You may need to manually set your language environment

#+begin_src sh
# export LANG=en_US.UTF-8
#+end_src

Preferred editor for local and remote sessions

#+begin_src sh
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi
#+end_src

Compilation flags

#+begin_src sh
# export ARCHFLAGS="-arch x86_64"
#+end_src

Set personal aliases, overriding those provided by oh-my-zsh libs, plugins, and themes. Aliases can be placed here, though oh-my-zsh users are encouraged to define aliases within the ZSH_CUSTOM folder. For a full list of active aliases, run `alias`.

Example aliases
#+begin_src sh
# alias zshconfig="mate $HOME/.zshrc"
# alias ohmyzsh="mate $HOME/.oh-my-zsh"
#+end_src

emacs

#+begin_src sh
alias doomsync="$HOME/.emacs.d/bin/doom sync"
alias doomdoctor="$HOME/.emacs.d/bin/doom doctor"
alias doomupgrade="$HOME/.emacs.d/bin/doom upgrade"
alias doompurge="$HOME/.emacs.d/bin/doom purge"
alias doomclean="$HOME/.emacs.d/bin/doom clean"
alias doomreset="rm -rf $HOME/.emacs.d/.local/straight && doomsync"
#+end_src

youtube-dl

#+begin_src sh
# alias yta-aac="youtube-dl --extract-audio --audio-format aac "
# alias yta-best="youtube-dl --extract-audio --audio-format best "
# alias yta-flac="youtube-dl --extract-audio --audio-format flac "
# alias yta-m4a="youtube-dl --extract-audio --audio-format m4a "
# alias yta-mp3="youtube-dl --extract-audio --audio-format mp3 "
# alias yta-opus="youtube-dl --extract-audio --audio-format opus "
# alias yta-vorbis="youtube-dl --extract-audio --audio-format vorbis "
# alias yta-wav="youtube-dl --extract-audio --audio-format wav "
# alias ytv-best="youtube-dl -f bestvideo+bestaudio "
#+end_src

To customize prompt, run `p10k configure` or edit $HOME/.p10k.zsh.

#+begin_src sh
[[ ! -f $HOME/.p10k.zsh ]] || source $HOME/.p10k.zsh
#+end_src

Set Variables
Syntax highlighting for man pages using bat

#+begin_src sh
export MANPAGER="sh -c 'col -bx | bat -l man -p'"
#+end_src

Change ZSH Options

* ALIASES
** Changing "ls" to "exa"

#+begin_src sh
alias ls='exa -alF --color=always --group-directories-first' # my preferred listing
alias la='exa -aF --color=always --group-directories-first'  # all files and dirs
alias ll='exa -lF --color=always --group-directories-first'  # long format
alias lt='exa -aT --level=2 --color=always --group-directories-first' # tree listing
alias l.='exa -a | egrep "^\."'
#+end_src

** yt-dlp

#+begin_src sh
alias yta-best="yt-dlp --extract-audio --audio-format best "
alias ytv-best="yt-dlp -f bestvideo+bestaudio --merge-output-format mkv "
alias ytd="yt-dlp -f "
alias ytl="yt-dlp -F "
#+end_src

** Open in Emacs

#+begin_src sh
alias doom-config="open -a emacs $HOME/.doom.d/config.org"
alias doom-pack="open -a emacs $HOME/.doom.d/packages.el"
alias doom-init="open -a emacs $HOME/.doom.d/init.el"
alias doom-open="open -a emacs "
alias zsh-config="open -a emacs $HOME/.zshrc"
alias emacs="open -a emacs"
#+end_src

** Scripts

#+begin_src sh
alias reformatvtt="python $HOME/.dotfiles/python-scripts/reformat-vtt.py"
#+end_src

** Shortcuts

#+begin_src sh
alias dev="cd $HOME/dev"
alias dotfiles="cd $HOME/.dotfiles"
alias newvlc="open -n /Applications/VLC.app"
#+end_src

** Random Aliases

#+begin_src sh
alias python="python3"
alias pip="pip3"
alias trail='<<<${(F)path}'
#+end_src

** Homebrew

#+begin_src sh
# alias brew="/opt/homebrew/bin/brew"
alias brewupdate="echo 'Updating Homebrew and Casks' && brew cu -af && echo 'Upgrading Packages' && brew upgrade"
#+end_src

** App Management

#+begin_src sh
alias updateapps="echo 'Updating Homebrew and Casks...' && brew cu -af && echo 'Upgrading Packages...' && brew upgrade && echo 'Updating Apps from App Store...' && mas upgrade && echo 'Updating Doom Emacs...' && doomupgrade"
alias deletezsh="echo 'Delete $HOME/.oh-my-zsh/custom' && rm $HOME/.oh-my-zsh/custom && echo 'Updating ZSH' && exec zsh -l"
alias linkzsh="echo 'Relink .oh-my-zsh/custom' && $HOME/.dotfiles/install && sleep 1s && exec zsh"
#+end_src

* Customize Prompt(s)

Add locations to $PATH variables

Write Handy Functions

#+begin_src sh
function mkcd() {
  mkdir -p "$@" && cd "$_";
}
#+end_src

Use ZSH Plugins

...and Other Surprises

To customize prompt, run `p10k configure` or edit $HOME/.dotfiles/p10k.zsh.

#+begin_src sh
[[ ! -f $HOME/.dotfiles/p10k.zsh ]] || source $HOME/.dotfiles/p10k.zsh
#+end_src

* Source External Shell Info

#+begin_src sh
if [ "$MACHINE_TYPE" = "work" ]; then
    source $HOME/.dotfiles/lib/aliases_work.zsh
else
    source $HOME/.dotfiles/lib/aliases_personal.zsh
fi

source $HOME/.dotfiles/private_info/private_info.zsh
#+end_src
