#!/usr/bin/env bash

SCRIPT_DIR="$HOME/.dotfiles/scripts"
source "$SCRIPT_DIR/utils"

_exists() {
  command -v "$1" >/dev/null 2>&1
}

# The check_exists function that uses _exists
check_exists() {
  if ! _exists "$1"; then
    error "$1 doesn't exist, please install..."
    exit 1
  fi
}

open_dmg_dir() {

  prompt "Open the dmg directory to manually install apps? [y/N] "
  read  -n 1 answer
  echo
  if [ "${answer}" != "y" ]; then
    echo "Skipping dmg manual install..."
    return 0
  fi

  open "$HOME/.dotfiles/dmgs"

  return 0
}

open_dmg_dir
